### ISSUE TITLE
Problem: docker_unicorn fails to start

### ISSUE THREAD

**Issue by weex** [magicstone-dev/acropolis#64]
With most recent commit, docker_unicorn fails with the following message:

```
unicorn_1   | bundler: failed to load command: unicorn (/diaspora/vendor/bundle/ruby/2.6.0/bin/unicorn)
unicorn_1   | ArgumentError: directory for pid=/diaspora/tmp/pids/web.pid not writable
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/configurator.rb:104:in `block in reload'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/configurator.rb:100:in `each'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/configurator.rb:100:in `reload'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/configurator.rb:78:in `initialize'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:78:in `new'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:78:in `initialize'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/bin/unicorn:128:in `new'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/gems/unicorn-6.0.0/bin/unicorn:128:in `<top (required)>'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `load'
unicorn_1   |   /diaspora/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `<top (required)>'
```
The error is clear enough but it looks like the image needs to be rebuilt with VOLUME /diaspora/tmp and the docker-compose.yml also providing that volume.

**Comment by weex** [comment]
Image didn't need to be rebuilt but the PR above adds the necessary volume entry.
